[package]
name = "placeholder-data-api"
version = "0.1.0"
authors = ["Yossi Spira <spira.joe214@gmail.com>"]
edition = "2018"

[dependencies]
tide = "0.15.0"
async-std = { version = "1.8.0", features = ["attributes"] }
serde = "1.0.80"
serde_derive = "1.0.80"
reqwest = "0.10.9"