name: Lint Python PR

on:
  pull_request:
    branches:
      - main
    paths:
      - "python/**"

jobs:
  lint-python:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up Python 3.8.2
        uses: actions/setup-python@v1
        with:
          python-version: 3.8.3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Linter
        run: pylint ./*.py